### PR TITLE
Do a little clean up of files and update the readme

### PR DESCRIPTION
**Pull request by Chocolate-Chip-Computing**
Good, but noticed you REMOVED MY WALLPAPERS DESU ;_;

Also, you have a tar command that does -C/tmp without a space between. I will be headding home soon, so I can better merge. Fucking web interface.

### CODE REVIEW

**Comment by Faalentijn** [comment]
Your wallpapers sucked. I replaced them with ones relevant to the board.

And there is -C/opt/tor on line 362 but the command works fine. I change the line for the next commit

**Comment by Chocolate-Chip-Computing** [comment]
Ok. I might leave SOME of the older wallpapers in my personal revisions. I'll get rid of the pony and furry ones. No more trolling ;_;

**Comment by Chocolate-Chip-Computing** [comment]
Also, I just noticed the removal of a default desktop background. Why? $HOME needs to expand, and that is why I had that as its own little script, btw.

**Comment by Chocolate-Chip-Computing** [comment]
Oh wait. I see what you did. Interesting. Are you sure there isn't a required order? Also, I'm p sure what you did will put it to the lowest line, which is identified as 

[trash://]

**Comment by Faalentijn** [comment]
There doesn't seem to be no. https://imgrush.com/85yKfxoUow1k.png

**Pull request merged**
