### PR TITLE
Add some random stuff. 

### PR DESCRIPTION
**Pull request by Faalentijn**

### CODE REVIEW

**Comment by Chocolate-Chip-Computing** [comment]
I will merge, but  I think that using hashed-word passwords is stupid. I'm not the only one who thinks this. If you are going through the trouble of making a hashed password that you'd never remember, why make it a hashed word instead of a random string? Anyway, I like your other documentation edits.

**Comment by Faalentijn** [comment]
Simply because it's easy to remember a word and what hash you used.

Although this does make your security rely on it being a secret. Which is bad (see How Software Work by No Starch Press^[1]). It does make for an easy to remember, secure passwords for things you won't be typing in that often (ie. root passwords).

[1] https://www.nostarch.com/howsoftwareworks

**Comment by Faalentijn** [comment]
Also there is still a lot of working needing to be done on the zsh one.

**Comment by Chocolate-Chip-Computing** [comment]
While I don't personally care about Window Managers, I care a lot about Desktop Environments. However, the audience of this script (The Friendly Linux Thread) care about both. I know nothing of Window Managers, but I do know a lot about DE options. I suggest you work more on the Window Managers at this time, just to get it over with.

**Comment by Faalentijn** [comment]
It's not something that you can get easily over with...

**Comment by Chocolate-Chip-Computing** [comment]
I forgot to say in my post: simple word hashes are decent enough for offline passwords, but having a hashed password for an online service is stupid because it is susceptible to a dictionary attack. Just read https://wiki.installgentoo.com/index.php/Passwords (of course I knew of this from other sources)

**Comment by Faalentijn** [comment]
They are talking about Rainbow Tables [1] which are not the same that I'm talking about. A lot of sites tend to hash the passwords and store them in a database to make it harder to crack.

However some people spend a lot of time pre-calculating hashes and putting them in a massive table. these are called rainbow tables. However if you hash a password and put it in as your password it will rehash it. And it's a lot less likely someone pre-calculated the hash of the hash of a password

" Hashing a word/phrase: This may get you a decent password length, but if you're going to use a tool, why not use a tool specific to making good passwords?" - Same page

[1] https://en.wikipedia.org/wiki/Rainbow_table

**Pull request merged**
